application: teaching-materials
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: 1h

- url: /htmlcss-1day/
  static_files: htmlcss-1day/index.html
  upload: htmlcss-1day/index.html

- url: /htmlcss-1day
  static_dir: htmlcss-1day

- url: /multimedia/
  static_files: multimedia/index.html
  upload: multimedia/index.html

- url: /multimedia
  static_dir: multimedia

- url: /data-modeling/
  static_files: data-modeling/index.html
  upload: data-modeling/index.html

- url: /data-modeling
  static_dir: data-modeling

- url: /htmlcss/
  static_files: htmlcss/index.html
  upload: htmlcss/index.html

- url: /htmlcss
  static_dir: htmlcss

- url: /javascript/
  static_files: javascript/index.html
  upload: javascript/index.html

- url: /javascript
  static_dir: javascript

- url: /exercises/
  static_files: exercises/index.html
  upload: exercises/index.html

- url: /exercises
  static_dir: exercises

- url: /git
  static_dir: git

- url: /cli
  static_dir: cli

- url: /dns
  static_dir: dns

- url: /domains
  static_dir: domains

- url: /hosting
  static_dir: hosting

- url: /common
  static_dir: common

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /
  static_files: index.html
  upload: index.html
